# Use the official Python image as the base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Python script into the container
COPY app/* .

# Expose port 80 for the web server
EXPOSE 80

# Define the command to run when the container starts
CMD ["python3", "app/app.py"]
